version: '3.8'

services:
  web:
    build: .
    command: gunicorn auth_project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DB_NAME: garnishment-db
      DB_USER: garnish-dev@garnish-dev1
      DB_PASSWORD: G@rnish-D3v
      DB_HOST: garnish-dev1.database.windows.net
      DB_PORT: 1433
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "RJ@12345"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
