# Generated by Django 5.1.5 on 2025-01-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0044_alter_company_details_co_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_details',
            old_name='co_id',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='company_details',
            old_name='DBA_name',
            new_name='dba_name',
        ),
    ]
