# Generated by Django 5.1.5 on 2025-01-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0045_rename_co_id_company_details_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer_profile',
            name='employer_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
