# Generated by Django 5.1.5 on 2025-01-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0047_employer_profile_cid_alter_employer_profile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer_profile',
            name='cid',
        ),
        migrations.AlterField(
            model_name='company_details',
            name='cid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='email',
            field=models.EmailField(default='rtt@gmail.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='employer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='employer_name',
            field=models.CharField(default='ABS', max_length=100),
        ),
    ]
